backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "home-page",
            }
          - label: Slider
            label_singular: Slide
            name: slider
            widget: list
            fields:
              - { label: Heading Line 1, name: heading1, widget: string }
              - {
                  label: Heading Line 2,
                  name: heading2,
                  widget: string,
                  required: false,
                }
              - { label: Subheading, name: subheading, widget: string }
              - label: Image
                name: image
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 850",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: "Services Area"
            name: servicesArea
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Blurb, name: blurb, widget: text }
              - label: Services
                label_singular: "Service"
                name: services
                widget: list
                fields:
                  - label: "Service"
                    name: "service"
                    widget: "relation"
                    collection: "services"
                    searchFields: ["title"]
                    valueField: "title"
                    displayFields: ["title"]
                    hint: Very important!!!! It has to be exactly the same name as of the service on the services colection
          - label: "About Me Area"
            name: aboutMeArea
            widget: object
            fields:
              - { label: Heading Line 1, name: heading1, widget: string }
              - {
                  label: Heading Line 2,
                  name: heading2,
                  widget: string,
                  required: false,
                }
              - label: Blurb
                name: blurb
                widget: object
                fields:
                  - label: Paragraphs
                    label_singular: "Paragraph"
                    name: paragraphs
                    widget: list
                    fields:
                      - { label: Paragraph, name: paragraph, widget: text }
              - label: "Person Picture"
                name: personPicture
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 492 x 699",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: "Articles Area"
            name: articlesArea
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Blurb, name: blurb, widget: text }
          - label: "Testimonials Area"
            name: testimonialsArea
            widget: object
            fields:
              - label: "Testimonials"
                label_singular: "Testimonial"
                name: testimonials
                widget: list
                fields:
                  - { label: Quote, name: quote, widget: text }
                  - { label: Author, name: author, widget: string }

      - file: "src/pages/about.md"
        label: "About Page"
        name: "aboutpage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "home-page",
            }
          - { label: "About Me Text", name: body, widget: markdown }
    editor:
      preview: false

  - name: "services"
    label: "Services"
    label_singular: "Service"
    folder: "src/pages/services"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "service-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Thumbnail Image"
        name: thumbnailimage
        widget: object
        required: false
        fields:
          - { label: Image, name: image, widget: image, hint: "80 x 90" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - label: "Banner Image"
        name: bannerimage
        widget: object
        required: false
        fields:
          - { label: Image, name: image, widget: image, hint: "1920 x 195" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - label: "Body Image"
        name: bodyimage
        widget: object
        required: false
        fields:
          - { label: Image, name: image, widget: image, hint: "370 x 490" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - label: "Testimonials Area"
        name: testimonialsArea
        widget: object
        fields:
          - label: "Testimonials"
            label_singular: "Testimonial"
            name: testimonials
            widget: list
            fields:
              - { label: Quote, name: quote, widget: text }
              - { label: Author, name: author, widget: string }
    editor:
      preview: false

  - name: "mindfulnessTraining"
    label: "Mindfulness Training"
    files:
      - file: "src/pages/services/mindfulness-training/mindfulness-based-stress-reduction-course.md"
        label: "Mindfulness-Based Stress Reduction Course"
        name: "mbsrc"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "mindfulness-training-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/services/mindfulness-training/mindfulness-based-pain-management-course.md"
        label: "Mindfulness-Based Pain Management Course"
        name: "mbpmc"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "mindfulness-training-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/services/mindfulness-training/frequently-asked-questions.md"
        label: "Frequently Asked Questions"
        name: "faq"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "mindfulness-training-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "List of Questions-Answers"
            label_singular: "Question-Answer"
            name: qa
            widget: list
            fields:
              - { label: Question, name: question, widget: text }
              - { label: Answer, name: answer, widget: text }

      - file: "src/pages/services/mindfulness-training/upcoming-courses.md"
        label: "Upcoming Courses Page"
        name: "upcomingCourses"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "mindfulness-training-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/general/mindfulness-training-menu.md"
        label: "Mindfulness Traing Menu"
        name: "mtMenu"
        fields:
          - label: Menu Items
            label_singular: "Menu Item"
            name: menuItems
            widget: list
            required: false
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Link,
                  name: link,
                  widget: string,
                  required: false,
                  hint: "Relative Path. Example: /about/, /contact/, /services/mindfulness-training/, ect..",
                }
    editor:
      preview: false

  - name: upcomingCourses
    label: "Upcoming Courses"
    label_singular: "course"
    folder: "src/general/upcoming-courses"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "upcoming-courses",
        }
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "tip: use a combination of course name and initial date of course"
      }
      - {
        label: "Name of Course",
        name: "courseName",
        widget: "relation",
        collection: "mindfulnessTraining",
        searchFields: ["title"],
        valueField: "title",
        displayFields: ["title"],
        hint: Very important!!!! It has to be exactly the same name as of the course on the Mindfulness Training colection
      }
      - {
          label: "Start Date of Event",
          name: "dateStart",
          widget: "date",
          default: "",
          dateFormat: "YYYY-MM-DD",
          hint: "YYYY-MM-DD",
        }
      - {
          label: "End Date of Event",
          name: "dateEnd",
          widget: "date",
          default: "",
          dateFormat: "YYYY-MM-DD",
          required: false,
          hint: "YYYY-MM-DD - Optional for 1-day courses.",
        }
      - {
        label: "Venu",
        name: "venue",
        widget: "string",
        required: false,
        hint: "Optional"
      }        
      - label: "Thumbnail Image"
        name: thumbnailimage
        widget: object
        required: false
        hint: Optional
        fields:
          - { label: Image, name: image, widget: image, hint: "500x500" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - { label: "Body", name: "body", widget: "markdown" }

    editor:
      preview: false

  - name: articles
    label: Articles
    label_singular: ArticleThumbnail
    folder: "src/pages/articles"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "date",
          dateFormat: "YYYY-MM-DD",
        }
      # format: "DD MM YYYY",
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - label: "Thumbnail Image"
        name: thumbnailimage
        widget: object
        required: false
        fields:
          - { label: Image, name: image, widget: image, hint: "1170 x 780" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - label: "Banner Image"
        name: bannerimage
        widget: object
        required: false
        fields:
          - { label: Image, name: image, widget: image, hint: "1920 x 195" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - label: "Body Image"
        name: bodyimage
        widget: object
        required: false
        fields:
          - { label: Image, name: image, widget: image, hint: "1170 x 780" }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
    editor:
      preview: false

  - name: "general"
    label: "General"
    files:
      - file: "src/general/logo.md"
        label: "Logo"
        name: "logo"
        fields:
          - { label: Image, name: image, widget: image }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - file: "src/general/contact-details.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - label: "Contact Details"
            name: contact_details
            widget: object
            fields:
              - label: Phone Number
                name: phone
                widget: object
                fields:
                  - {
                      label: Display,
                      name: phonedisplay,
                      widget: string,
                      hint: "Example: 033 330 6121",
                    }
                  - {
                      label: Number,
                      name: phonenumber,
                      widget: string,
                      hint: "Example: +27333306121",
                    }
              - { label: Physical Address, name: address, widget: string }
              - { label: Email Address, name: email, widget: string }

      - file: "src/general/appointment-area.md"
        label: "Appointment Area"
        name: "appointmentArea"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Blurb, name: blurb, widget: text }

      - file: "src/general/social.md"
        label: "Social Media"
        name: "social"
        fields:
          - { label: Facebook Page Url, name: facebook, widget: string }

      - file: "src/general/main-menu.md"
        label: "Main Menu"
        name: "mainMenu"
        fields:
          - label: Menu Items
            label_singular: "Menu Item"
            name: menuItems
            widget: list
            required: false
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Link,
                  name: link,
                  widget: string,
                  required: false,
                  hint: "Relative Path. Example: /about/, /contact/, /services/mindfulness-training/, ect..",
                }
              - label: Sub Menu
                name: subMenu
                widget: object
                required: false
                fields:
                  - label: Sub Menu menuItems
                    label_singular: Sub Menu Item
                    name: subMenuItems
                    widget: list
                    fields:
                      - { label: Name, name: name, widget: string }
                      - {
                          label: Link,
                          name: link,
                          widget: string,
                          required: false,
                          hint: "Relative Path. Example: /about/, /contact/, /services/mindfulness-training/, ect..",
                        }
                      - label: Sub Menu
                        name: subMenu
                        widget: object
                        required: false
                        fields:
                          - label: Sub Menu menuItems
                            label_singular: Sub Menu Item
                            name: subMenuItems
                            widget: list
                            fields:
                              - { label: Name, name: name, widget: string }
                              - {
                                  label: Link,
                                  name: link,
                                  widget: string,
                                  hint: "Relative Path. Example: /about/, /contact/, /services/mindfulness-training/, ect..",
                                }
    editor:
      preview: false
