backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: "general"
    label: "General"
    files:
      - file: "src/general/contact.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - label: "Contact Details"
            name: contact_details
            widget: object
            fields:
              - label: Phone Number
                name: phone
                widget: object
                fields:
                  - {
                      label: Display,
                      name: phonedisplay,
                      widget: string,
                      hint: "Example: 033 330 6121",
                    }
                  - {
                      label: Number,
                      name: phonenumber,
                      widget: string,
                      hint: "Example: +27333306121",
                    }
              - { label: Physical Address, name: address, widget: string }
              - { label: Email Address, name: email, widget: string }
    editor:
      preview: false
