backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: articles
    label: Articles
    label_singular: Article
    folder: "src/pages/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "date",
          dateFormat: "YYYY-MM-DD",
        }
      # format: "DD MM YYYY",
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "home-page",
            }
          - label: Slider
            label_singular: Slide
            name: slider
            widget: list
            fields:
              - { label: Heading Line 1, name: heading1, widget: string }
              - {
                  label: Heading Line 2,
                  name: heading2,
                  widget: string,
                  required: false,
                }
              - { label: Subheading, name: subheading, widget: string }
              - label: Image
                name: image
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 850",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: "Services Area"
            name: servicesArea
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Blurb, name: blurb, widget: text }
              - label: "Services"
                label_singular: "Service"
                name: services
                widget: list
                fields:
                  - label: Service Icon
                    name: serviceIcon
                    widget: object
                    fields:
                      - {
                          label: Image,
                          name: image,
                          widget: image,
                          hint: "size 80 x 90",
                        }
                      - {
                          label: Title,
                          name: alt,
                          widget: text,
                          hint: "Please inform. Important for SEO",
                        }
                  - { label: Heading, name: heading, widget: string }
                  - { label: Blurb, name: blurb, widget: text }
          - label: "About Me Area"
            name: aboutMeArea
            widget: object
            fields:
              - { label: Heading Line 1, name: heading1, widget: string }
              - {
                  label: Heading Line 2,
                  name: heading2,
                  widget: string,
                  required: false,
                }
              - { label: Blurb, name: blurb, widget: text }
              - label: "Person's Picture"
                name: personPicture
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 492 x 699",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: "Testimonials Area"
            name: testimonialsArea
            widget: object
            fields:
              - label: "Testimonials"
                label_singular: "Testimonial"
                name: testimonials
                widget: list
                fields:
                  - { label: Quote, name: Quote, widget: text }

  - name: "general"
    label: "General"
    files:
      - file: "src/general/logo.md"
        label: "Logo"
        name: "logo"
        fields:
          - { label: Image, name: image, widget: image }
          - {
              label: Title,
              name: alt,
              widget: text,
              hint: "Please inform. Important for SEO",
            }
      - file: "src/general/contact.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - label: "Contact Details"
            name: contact_details
            widget: object
            fields:
              - label: Phone Number
                name: phone
                widget: object
                fields:
                  - {
                      label: Display,
                      name: phonedisplay,
                      widget: string,
                      hint: "Example: 033 330 6121",
                    }
                  - {
                      label: Number,
                      name: phonenumber,
                      widget: string,
                      hint: "Example: +27333306121",
                    }
              - { label: Physical Address, name: address, widget: string }
              - { label: Email Address, name: email, widget: string }
      - file: "src/general/social.md"
        label: "Social Media"
        name: "social"
        fields:
          - { label: Facebook Page Url, name: facebook, widget: string }
    editor:
      preview: false
